apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-voting-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
data:
  DB_HOST: "db"
  REDIS_HOST: "redis"
  POSTGRES_HOST: "db"
