apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: db
    {{- include "voting-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        {{- include "voting-app.labels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: {{ .Values.postgres.containerPort }}
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-voting-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-voting-secret
              key: postgres-password
