apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
  - name: http
    port: {{ .Values.resultApp.servicePort }}
    targetPort: {{ .Values.resultApp.containerPort }}
    nodePort: {{ .Values.resultApp.nodePort }}
