apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-voting-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
