apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: voting-app
    {{- include "voting-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.votingApp.replicas }}
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
        {{- include "voting-app.labels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
      - name: voting-container
        image: {{ .Values.votingApp.image }}
        ports:
        - containerPort: {{ .Values.votingApp.containerPort }}
          name: web
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-voting-config
        env:
        - name: OPTION_A
          value: {{ .Values.votingApp.optionA | quote }}
        - name: OPTION_B
          value: {{ .Values.votingApp.optionB | quote }}
